version: '3'
services:
  rca-web:
    image: nginx:1.14
    volumes:
     - ./log:/var/log/nginx
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ./config:/etc/nginx/conf.d/
     - ./build:/home/web
#     - ./web_en:/home/web_en
    ports:
     - "3000:3000"
    container_name: rca-web
    restart: unless-stopped
